theme: jekyll-theme-minimal
title: My IT Security Portfolio
description: Showcasing my cybersecurity projects, certifications, and skills.
logo: /assets/profile.png # Add your profile image later
show_downloads: false
